#!/bin/sh

clear

bash ./do_watch.sh

echo "Watching for python file changes..."

watchmedo shell-command \
  --patterns="./src/*.py;./tests/*;./tox.ini;./requirements.txt;./requirements-dev.txt;./setup.py" \
  --recursive \
  --drop \
  --command="clear; bash ./do_watch.sh; echo \"Watching for python file changes...\""
